---
- name: Install git
  apt:
    name: git

- name: Create app directory
  file:
    name: /app
    state: directory

- name: Clone app from github
  git:
    dest=/app
    repo=https://github.com/Kixeye/testapp.git

- name: Untar testapp.tar
  unarchive:
    src: /app/testapp.tar
    dest: /app

- name: Run webserver
  command: java -cp /app/testapp.jar kixeye.testapp.Main
